version: '2'
services: 
    db:
        container_name: mongodb-$APP_NAME-$BUILD_NUMBER
        image: mongo:latest
        #environment:
        ports: 
            - 27017
    app:
        container_name: $APP_NAME-$BUILD_NUMBER
        image: $IMAGE_NAME:$BUILD_NUMBER
        network_mode: "service:db"
        environment: 
            - NODE_SECRET=bukitPanjang993
            - NODE_ENV=test
        command: ./scrips/docker_command.sh
